Merge develop into master
GiethoornInternationalHarbor/Container pull request #1
Opened 2018-05-16 21:57 UTC by Aplicticus

2018-05-17 08:11 UTC, DanielvanBavel submitted a review, later dismissed

2018-05-17 08:45 UTC, markieo1 requested changes

2018-05-17 08:45 UTC, markieo1 commented on ContainerService.App/Messaging/ContainerMessageHandler.cs
> +			await _containerRepository.SortContainersAsync(receivedShip.Containers);
This only need to happen when a service is requested, for loading or unloading

2018-05-17 08:45 UTC, markieo1 commented on ContainerService.Core/Models/Truck.cs
> +		public string LicensePlate { get; set; }
Truck can also contain a container. See TransportationService for this.

2018-05-17 08:45 UTC, markieo1 commented on ContainerService.Infrastructure/Repositories/ContainerRepository.cs
> +			return await Task.Run(() => containers);
Unloading containers happens on available trucks

2018-05-17 09:56 UTC, markieo1 requested changes

2018-05-17 09:56 UTC, markieo1 commented on ContainerService.Infrastructure/Repositories/ContainerRepository.cs
> +			return await Task.Run(() => containers);
make sure to prioritize lifestock see: [order list](https://stackoverflow.com/questions/3309188/how-to-sort-a-listt-by-a-property-in-the-object)

2018-05-17 16:25 UTC, markieo1 requested changes

2018-05-17 16:25 UTC, markieo1 commented on ContainerService.App/Messaging/ContainerMessageHandler.cs
> +					await _containerRepository.LoadContainerAsync(selectedTruck.Container);
Don't we need to do this for every truck?

2018-05-17 16:25 UTC, markieo1 commented on ContainerService.Core/Models/Container.cs
> +		public ContainerZone ContainerZone { get; set; }
What is the usage of this?

2018-05-19 11:41 UTC, markieo1 requested changes

2018-05-19 11:41 UTC, markieo1 commented on ContainerService.Infrastructure/Repositories/ContainerRepository.cs
> +			containers.OrderBy(x => x.ProductType == ProductType.FreshProduceAndLivestock);
This won't work

2018-05-19 11:41 UTC, markieo1 commented on ContainerService.Core/Models/ProductType.cs
> +		FreshProduceAndLivestock,
Add = 1, or =2

2018-05-19 11:41 UTC, markieo1 commented on ContainerService.Infrastructure/Repositories/ContainerRepository.cs
> +			containers.OrderBy(x => x.ProductType == ProductType.FreshProduceAndLivestock);
This won't work, see: [C# Sort List by Enum
](https://stackoverflow.com/a/42552327/3563975)

2018-05-19 11:45 UTC, markieo1 requested changes

2018-05-19 11:45 UTC, markieo1 commented on ContainerService.Infrastructure/Repositories/ContainerRepository.cs
> +			containers.OrderByDescending(x => (int)(x.ProductType)).ToArray();
This should still be OrderBy, else we prioritize `ProductType.Normal`

2018-05-19 11:46 UTC, markieo1 approved these changes

2018-05-19 11:48 UTC, merged